In [1]:
import pandas
import os

In [2]:
import utils

In [21]:
import os
from math import radians, cos, sin, asin, sqrt
import sys
import time

import sys
sys.path.append('/Users/gustaveronteix/Documents/Projets/Projets Code/batch7_beges/datasets/chorus-dt')

import requests
import dill
import urllib.parse
import pandas as pd
from tqdm import tqdm
from utils.config import CONFIG

from utils import dataset
from utils.resolvers import HardcodesResolver, GeocodingApiResolver

tqdm.pandas()


def compute_distance(x):
    lon1 = x["coords_place_0_lon"]
    lat1 = x["coords_place_0_lat"]
    lon2 = x["coords_place_1_lon"]
    lat2 = x["coords_place_1_lat"]
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    c = 2 * asin(sqrt(a))
    r = 6371  # Radius of earth in miles. Use 6371 for kilometers
    return c * r


if __name__ == "__main__":
    data = dataset.load_data("./data/raw/sample-avion-train.csv")
    places, trips = dataset.get_places_and_trips(data, ["T", "TC", "TCA", "TCM", "TU"])

    # Splitting codes / name
    places[["code_1", "name", "temp", "code_2"]] = places["place"].str.extract(
        "([^-]*)\s-\s([^\[]*)\s?([\[](.*)[\]])?", expand=True
    )
    places.drop(columns=["temp"], inplace=True)

    places["resolved"] = False
    places["resolved_through_uic_code"] = False
    places["resolved_through_insee_code"] = False
    places["resolved_through_tvs_code"] = False
    places["resolved_through_iata_code"] = False
    places["resolved_through_gmap_api"] = False
    places["lon"] = None
    places["address"] = ""
    places["lat"] = None

    hardcode_resolver = HardcodesResolver()
    places = places.progress_apply(hardcode_resolver.resolve, axis=1)

    # Initiate geocoder
    GMAP_API_KEY = CONFIG["api_keys"]["gmap"]
    geocoding_api_resolver = GeocodingApiResolver(api_name="gmap", api_key=GMAP_API_KEY)

    # Apply the geocoder with delay using the rate limiter:
    places.loc[~places["resolved"], :] = places[~places["resolved"]].progress_apply(
        geocoding_api_resolver.resolve, axis=1
    )
    geocoding_api_resolver.save_cache()
    for c in places:
        if "resolved_through_" in c:
            print(c, places[c].sum())

    places["lat"] = places["lat"].astype(float)
    places["lon"] = places["lon"].astype(float)
    places_dict = places.set_index("place").to_dict()

    for place_index in [0, 1, 2]:
        trips["coords_place_%d_lat" % place_index] = trips[
            "trip_place_%d" % place_index
        ].apply(lambda x: places_dict["lat"][x])
        trips["coords_place_%d_lon" % place_index] = trips[
            "trip_place_%d" % place_index
        ].apply(lambda x: places_dict["lon"][x])
        trips["coords_place_%d" % place_index] = (
            trips["coords_place_%d_lon" % place_index].astype(str)
            + ";"
            + trips["coords_place_%d_lat" % place_index].astype(str)
        )
        trips["place_%d_count" % place_index] = trips[
            "trip_place_%d" % place_index
        ].apply(lambda x: places_dict["total"][x])

    trips["distance"] = trips.apply(compute_distance, axis=1)
    places.to_csv("./data/clean/places.csv", index=False)
    trips.to_csv("./data/clean/trips.csv", index=False)

/Users/gustaveronteix/opt/anaconda3/lib/python3.7/site-packages/tqdm/std.py:658: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel

Prestation types:
['T' 'TU' 'TCA' 'TC']
Unique places src:  1009
Unique places dst:  1001
Unique places stop:  1409
Unique places:  1668
Unique trips:  16574

100%|██████████| 1668/1668 [00:00<00:00, 3958.85it/s]
  0%|          | 0/359 [00:00<?, ?it/s]

nan

100%|██████████| 359/359 [00:00<00:00, 1478.64it/s]

resolved_through_uic_code 98
resolved_through_insee_code 884
resolved_through_tvs_code 0
resolved_through_iata_code 327
resolved_through_gmap_api 357

In [16]:
import numpy as np

data = dataset.load_data("./data/raw/sample-avion-train.csv")
places, trips = dataset.get_places_and_trips(data, ["T", "TC", "TCA", "TCM", "TU"])

Prestation types:
['A' 'AU' 'AM']
Unique places src:  312
Unique places dst:  310
Unique places stop:  1
Unique places:  327
Unique trips:  1157

In [22]:
places

,place,src,dst,stop,total,code_1,name,code_2,resolved,resolved_through_uic_code,resolved_through_insee_code,resolved_through_tvs_code,resolved_through_iata_code,resolved_through_gmap_api,lon,address,lat
0,TR_FRPNO - Paris Nord,3212.0,3190.0,194.0,6596.0,TR_FRPNO,Paris Nord,NaN,True,False,False,False,False,True,2.355314,"Gare du Nord, 18 Rue de Dunkerque, 75010 Paris...",48.880948
1,75056 - PARIS,3060.0,3173.0,8266.0,14499.0,75056,PARIS,NaN,True,False,False,False,False,True,2.352222,"Paris, France",48.856614
2,TR_FRPLY - Paris Gare De Lyon,2949.0,2924.0,700.0,6573.0,TR_FRPLY,Paris Gare De Lyon,NaN,True,False,False,False,True,False,-86.300499,,41.365101
3,TR_FRPMO - Paris Montparnasse 1 Et 2,2451.0,2458.0,700.0,5609.0,TR_FRPMO,Paris Montparnasse 1 Et 2,NaN,True,False,False,False,True,False,13.091000,,38.175999
4,TR_BEBMI - BRUXELLES MIDI,1969.0,1985.0,1294.0,5248.0,TR_BEBMI,BRUXELLES MIDI,NaN,True,False,False,False,True,False,-88.915901,,40.477100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1663,64109 - BENEJACQ,0.0,0.0,1.0,1.0,64109,BENEJACQ,NaN,True,False,True,False,False,False,-0.190129,,43.194637
1664,33364 - SAILLANS,0.0,0.0,1.0,1.0,33364,SAILLANS,NaN,True,False,True,False,False,False,-0.271169,,44.957046
1665,27056 - BERNAY,0.0,0.0,1.0,1.0,27056,BERNAY,NaN,True,False,True,False,False,False,0.589592,,49.092588
1666,38516 - TRONCHE,0.0,0.0,1.0,1.0,38516,TRONCHE,NaN,True,False,True,False,False,False,5.743433,,45.210441
1667,59122 - CAMBRAI,0.0,0.0,1.0,1.0,59122,CAMBRAI,NaN,True,False,True,False,False,False,3.242210,,50.170278

In [23]:
places[places['resolved_through_iata_code']]

,place,src,dst,stop,total,code_1,name,code_2,resolved,resolved_through_uic_code,resolved_through_insee_code,resolved_through_tvs_code,resolved_through_iata_code,resolved_through_gmap_api,lon,address,lat
2,TR_FRPLY - Paris Gare De Lyon,2949.0,2924.0,700.0,6573.0,TR_FRPLY,Paris Gare De Lyon,NaN,True,False,False,False,True,False,-86.300499,,41.365101
3,TR_FRPMO - Paris Montparnasse 1 Et 2,2451.0,2458.0,700.0,5609.0,TR_FRPMO,Paris Montparnasse 1 Et 2,NaN,True,False,False,False,True,False,13.091000,,38.175999
4,TR_BEBMI - BRUXELLES MIDI,1969.0,1985.0,1294.0,5248.0,TR_BEBMI,BRUXELLES MIDI,NaN,True,False,False,False,True,False,-88.915901,,40.477100
5,TR_FRLPD - Lyon Part Dieu,1049.0,1032.0,661.0,2742.0,TR_FRLPD,Lyon Part Dieu,NaN,True,False,False,False,True,False,-69.579700,,-1.328610
6,TR_FRPST - Paris Est,804.0,821.0,153.0,1778.0,TR_FRPST,Paris Est,NaN,True,False,False,False,True,False,-75.658302,,20.735001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1647,IA_DKR - DAKAR,0.0,0.0,1.0,1.0,IA_DKR,DAKAR,NaN,True,False,False,False,True,False,-17.490200,,14.739700
1651,IA_SEN - SOUTHEND,0.0,0.0,1.0,1.0,IA_SEN,SOUTHEND,NaN,True,False,False,False,True,False,0.695556,,51.571400
1654,IA_JER - JERSEY,0.0,0.0,1.0,1.0,IA_JER,JERSEY,NaN,True,False,False,False,True,False,-2.195510,,49.207901
1656,IA_DUS - DUSSELDORF,0.0,0.0,1.0,1.0,IA_DUS,DUSSELDORF,NaN,True,False,False,False,True,False,6.766780,,51.289501
1660,TR_FRLLE - LILLE EUROPE,0.0,0.0,1.0,1.0,TR_FRLLE,LILLE EUROPE,NaN,True,False,False,False,True,False,31.576700,,-25.430000

In [24]:
if __name__ == "__main__":
    data = dataset.load_data("./data/raw/sample-avion-train.csv")
    places, trips = dataset.get_places_and_trips(data, ["T", "TC", "TCA", "TCM", "TU"])

    # Splitting codes / name
    places[["code_1", "name", "temp", "code_2"]] = places["place"].str.extract(
        "([^-]*)\s-\s([^\[]*)\s?([\[](.*)[\]])?", expand=True
    )
    places.drop(columns=["temp"], inplace=True)

    places["resolved"] = False
    places["resolved_through_uic_code"] = False
    places["resolved_through_insee_code"] = False
    places["resolved_through_tvs_code"] = False
    places["resolved_through_iata_code"] = False
    places["resolved_through_gmap_api"] = False
    places["lon"] = None
    places["address"] = ""
    places["lat"] = None

    #hardcode_resolver = HardcodesResolver()
    #places = places.progress_apply(hardcode_resolver.resolve, axis=1)

Prestation types:
['T' 'TU' 'TCA' 'TC']
Unique places src:  1009
Unique places dst:  1001
Unique places stop:  1409
Unique places:  1668
Unique trips:  16574

In [9]:
a = places.loc[0]
with open(("./data/prepared/iata_codes.pkl"), "rb") as file_id:
    iata_codes = dill.load(file_id)

In [34]:
a["code_1"][:2]

'TR'

In [33]:
(a["code_1"][-3:] in iata_codes['lon']) & (a["code_1"][:2] == 'IA')

False

In [70]:
(a["code_1"][-3:] in iata_codes['lon']) & (a["code_1"][:2] == 'IA')
a["lon"] = iata_codes["lon"][a["code_1"][-3:]]
a["lat"] = iata_codes["lat"][a["code_1"][-3:]]

In [71]:
class HardcodesResolver:
    def __init__(self):
        self.insee_codes = self.load_codes("./data/prepared/insee_codes.pkl")
        self.tvs_codes = self.load_codes("./data/prepared/tvs_codes.pkl")
        self.uic_codes = self.load_codes("./data/prepared/uic_codes.pkl")
        self.iata_codes = self.load_codes("./data/prepared/iata_codes.pkl")

    def load_codes(self, path):
        with open(path, "rb") as file_id:
            return dill.load(file_id)

    def resolve(self, x):
        code_2_as_int = self.get_int(x["code_2"])
        
        try:
            if code_2_as_int and (code_2_as_int in self.uic_codes["lon"]):
                x["lon"] = self.uic_codes["lon"][code_2_as_int]
                x["lat"] = self.uic_codes["lat"][code_2_as_int]
                x["resolved"] = True
                x["resolved_through_uic_code"] = True
            elif x["code_1"] in self.insee_codes["lon"]:
                x["lon"] = self.insee_codes["lon"][x["code_1"]]
                x["lat"] = self.insee_codes["lat"][x["code_1"]]
                x["resolved"] = True
                x["resolved_through_insee_code"] = True
            elif (str(x["code_1"][-3:]) in self.iata_codes["lon"]) &
                (str(x["code_1"][:2]) == 'IA'):                
                x["lon"] = self.iata_codes["lon"][x["code_1"][-3:]]
                x["lat"] = self.iata_codes["lat"][x["code_1"][-3:]]
                x["resolved"] = True
                x["resolved_through_iata_code"] = True
            elif x["place"] == '-75056': # Hard exception...
                x["name"] = 'Paris'
            # elif x['code_1'] in TVS_CODES['lon']:
            #     x['lon'] = TVS_CODES['lon'][x['code_1']]
            #     x['lat'] = TVS_CODES['lat'][x['code_1']]
            #     x['resolved'] = True
            #     x['resolved_through_tvs_code'] = True
            else:
                x["lon"] = None
                x["lat"] = None
                
        except:
            print(x["code_1"])
        return x

    def get_int(self, x):
        try:
            return int(x)
        except ValueError:
            return None